path: /kaggle/working/Galaxy-Morphology-Detection/Data
train: Images/Train 
val: Images/Train

names:
  0: in_between_smooth
  1: edge_on
  2: cigar_shape
  3: spiral_shape
  4: completely_round_smooth